/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/fE8jCkJa4Rd
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function HouseDetailsForm() {
  return (
    <Card className="w-full max-w-md mx-auto">
      <CardHeader>
        <CardTitle>House Information</CardTitle>
        <CardDescription>Please enter the details about the house you are caring for.</CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="grid grid-cols-1 gap-4">
          <div className="space-y-2">
            <Label htmlFor="caretaker-number">Caretaker Number</Label>
            <Input id="caretaker-number" placeholder="Enter caretaker number" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="house-location">House Location</Label>
            <Input id="house-location" placeholder="Enter house location" />
          </div>
        </div>
        <div className="space-y-2">
          <Label htmlFor="house-name">House Name</Label>
          <Input id="house-name" placeholder="Enter house name" />
        </div>
        <div className="space-y-2">
          <Label htmlFor="house-type">House Type</Label>
          <Select>
            <SelectTrigger>
              <SelectValue placeholder="Select house type" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="1-bedroom">1 Bedroom</SelectItem>
              <SelectItem value="2-bedroom">2 Bedroom</SelectItem>
              <SelectItem value="bedsitter">Bedsitter</SelectItem>
              <SelectItem value="single">Single</SelectItem>
            </SelectContent>
          </Select>
        </div>
        <div className="space-y-2">
          <Label htmlFor="house-description">House Description</Label>
          <Textarea id="house-description" placeholder="Enter house description" />
        </div>
        <div className="space-y-2">
          <Label htmlFor="house-image">House Image</Label>
          <Input id="house-image" type="file" />
        </div>
      </CardContent>
      <CardFooter className="flex justify-end">
        <Button type="submit">Save</Button>
      </CardFooter>
    </Card>
  )
}
